export type DemoGuideStep = {
  id: string;
  route: string;
  target: string;
  title: string;
  whatIsIt: string;
  howToUse: string;
  rationale: string;
  studentBenefit: string;
  teacherBenefit: string;
  judgeFocus: string[];
  allowInteraction: boolean;
  // screen to set in useAppStore when navigating to "/"
  appScreen?: 'dashboard' | 'study' | 'game' | 'pretest';
  nextRoute?: string;
};

export const DEMO_GUIDE_STEPS: DemoGuideStep[] = [
  {
    id: "demo-toolbar",
    route: "/demo",
    target: "demo-toolbar",
    title: "Demo Toolbar",
    whatIsIt: "แถบควบคุมพิเศษที่แสดงเฉพาะบัญชี Demo",
    howToUse: "ใช้สำหรับกลับสู่ Demo Center, ข้ามขั้นตอนแบบลัด หรือจำลองผลลัพธ์ต่าง ๆ โดยไม่ต้องเล่นเองจนจบ",
    rationale: "ออกแบบมาเพื่อลดเวลาในการสาธิตระบบให้กรรมการหรือผู้บริหาร โดยไม่ต้องทำข้อสอบจริงทั้งหมด",
    studentBenefit: "ไม่มีผลกับนักเรียน เพราะนักเรียนจะไม่เห็นแถบนี้และไม่สามารถข้ามขั้นตอนได้",
    teacherBenefit: "ครูสามารถใช้เป็นเครื่องมือนำเสนอระบบได้อย่างรวดเร็ว",
    judgeFocus: ["สังเกตปุ่ม 'จำลองผล' ว่าสามารถเปลี่ยนค่าใน Demo Store ได้ทันทีโดยไม่กระทบฐานข้อมูลจริง"],
    allowInteraction: true,
  },
  {
    id: "demo-center",
    route: "/demo",
    target: "demo-center",
    title: "Demo Center",
    whatIsIt: "หน้ารวมฟังก์ชันทั้งหมดของระบบเพื่อการเข้าถึงที่รวดเร็ว",
    howToUse: "กดเพื่อเลือกเปิด Pre-test, ด่าน, กิจกรรม หรือ Dashboard ได้ทันที",
    rationale: "กรรมการอาจมีเวลาจำกัด จึงต้องมีศูนย์กลางในการเข้าถึงแต่ละโมดูลได้โดยตรง",
    studentBenefit: "การทดลองในโหมดนี้ไม่รบกวนเส้นทางการเรียนและฐานข้อมูลของนักเรียนจริง",
    teacherBenefit: "ใช้เป็นจุดเริ่มต้นในการนำเสนอระบบแบบเจาะจงบางประเด็น",
    judgeFocus: ["ทดลองกดเข้าฟังก์ชันต่าง ๆ ผ่านทางลัดในหน้านี้"],
    allowInteraction: true,
  },
  {
    id: "pretest-start",
    route: "/",
    target: "pretest-start",
    appScreen: "pretest",
    title: "ปุ่มเริ่ม Pre-test",
    whatIsIt: "จุดเริ่มต้นสำหรับวัดพื้นฐานคำศัพท์ก่อนเรียน",
    howToUse: "กดเริ่มทำแบบทดสอบ (หรือใน Demo สามารถกดข้ามได้)",
    rationale: "ผู้เรียนแต่ละคนมีความรู้เดิมไม่เท่ากัน ระบบจึงประเมินก่อนเพื่อกำหนดระดับเริ่มต้น",
    studentBenefit: "ได้รับคำถามที่เหมาะกับพื้นฐาน ไม่รู้สึกว่าเนื้อหายากหรือง่ายเกินไป",
    teacherBenefit: "ครูเห็นข้อมูลพื้นฐานก่อนเรียนและนำไปเปรียบเทียบพัฒนาการในภายหลังได้",
    judgeFocus: ["ระบบสุ่มคำถามมาจากคลังคำศัพท์ และเก็บเวลาในการทำ"],
    allowInteraction: true,
  },
  {
    id: "student-dashboard",
    route: "/",
    target: "student-dashboard",
    appScreen: "dashboard",
    title: "Student Dashboard",
    whatIsIt: "หน้าจอข้อมูลส่วนตัวของนักเรียน",
    howToUse: "เปิดดูสรุป Accuracy, ด่านปัจจุบัน, คำที่ผิดบ่อย",
    rationale: "ส่งเสริมให้ผู้เรียนกำกับการเรียนรู้ของตนเอง (Self-regulated Learning)",
    studentBenefit: "เห็นจุดแข็ง จุดที่ต้องปรับปรุง ไม่ต้องรอครูบอก",
    teacherBenefit: "ใช้เป็นหลักฐานในการพูดคุยให้คำปรึกษาแบบตัวต่อตัว",
    judgeFocus: ["ข้อมูลที่แสดงผลมีการอัปเดตแบบ Real-time หลังจากทำกิจกรรม"],
    allowInteraction: true,
  },
  {
    id: "rank-score",
    route: "/",
    target: "rank-score",
    appScreen: "dashboard",
    title: "ระบบ Rank (ความก้าวหน้า)",
    whatIsIt: "ระดับพัฒนาการรวมของผู้เรียน",
    howToUse: "ดูความก้าวหน้าและแถบเปอร์เซ็นต์สู่ Rank ถัดไป",
    rationale: "ไม่ควรใช้ตัวชี้วัดเดียวตัดสินผู้เรียน Rank จึงคำนวณจากหลายแกน (ด่าน, Accuracy, ดาว, สม่ำเสมอ)",
    studentBenefit: "เห็นว่าตนเองต้องพัฒนาด้านใดเพื่อเพิ่ม Rank ทำให้มีเป้าหมายรอบด้าน",
    teacherBenefit: "ดูแนวโน้มพัฒนาการ (Trend) โดยพิจารณาหลายองค์ประกอบ",
    judgeFocus: ["ลองกด 'จำลองผล' เปลี่ยน Rank เพื่อดูความเปลี่ยนแปลงทาง UI"],
    allowInteraction: true,
  },
  {
    id: "coin-exp",
    route: "/",
    target: "coin-exp",
    appScreen: "dashboard",
    title: "Coin และ EXP",
    whatIsIt: "สกุลเงินในเกม (Coin) และค่าประสบการณ์ (EXP)",
    howToUse: "เล่นกิจกรรมเพื่อสะสม นำ Coin ไปซื้อการ์ด",
    rationale: "เป็นกลไกพื้นฐานของ Gamification เพื่อสร้าง Loop การเล่น",
    studentBenefit: "ได้รับรางวัลทันที (Instant Gratification) ทำให้ไม่รู้สึกเหนื่อยกับการเรียน",
    teacherBenefit: "ใช้ดูระดับ 'การมีส่วนร่วม' (Engagement) เพราะ EXP ขึ้นเรื่อยๆ ตราบใดที่เล่น",
    judgeFocus: ["EXP และ Coin จะเพิ่มขึ้นเสมอ แต่ไม่ใช่ตัวแทนของคะแนนสอบ"],
    allowInteraction: false,
  },
  {
    id: "leaderboard",
    route: "/",
    target: "leaderboard",
    appScreen: "dashboard",
    title: "Leaderboard",
    whatIsIt: "ตำแหน่งเมื่อเปรียบเทียบกับผู้เล่นคนอื่นในห้อง",
    howToUse: "ดูใน Dashboard หลัก",
    rationale: "Rank คือพัฒนาการส่วนตัว แต่ Leaderboard คืออันดับเทียบกับกลุ่ม เพื่อสร้างแรงจูงใจเชิงบวก",
    studentBenefit: "แข่งขันกับเพื่อนอย่างสนุกสนาน",
    teacherBenefit: "ใช้สร้างบรรยากาศ Gamification ในชั้นเรียน แต่ไม่แนะนำให้ใช้แทนคะแนนเก็บ",
    judgeFocus: ["แสดงเพื่อนร่วมห้องจำลองในโหมด Demo"],
    allowInteraction: false,
  },
  {
    id: "stage-map",
    route: "/",
    target: "stage-map",
    appScreen: "dashboard",
    title: "Stage Map",
    whatIsIt: "แสดงเส้นทางการเรียนรู้แบบเป็นด่าน (100 ด่าน)",
    howToUse: "เลื่อนดูด่านต่าง ๆ และกดด่านที่ปลดล็อกเพื่อเข้าเล่น",
    rationale: "การแบ่งเนื้อหาเป็นเป้าหมายย่อย (Chunking) ช่วยให้ผู้เรียนเห็นความก้าวหน้าและไม่รู้สึกว่าเนื้อหามีขนาดใหญ่เกินไป",
    studentBenefit: "เห็นด่านปัจจุบัน ด่านที่ผ่านแล้ว และเป้าหมายถัดไปชัดเจน",
    teacherBenefit: "เห็นความแตกต่างของความก้าวหน้าระหว่างผู้เรียน และตรวจพบเด็กที่ติดด่านนานได้",
    judgeFocus: ["ด่านที่ยังไม่ถึงจะล็อกอยู่ ด่านที่ผ่านแล้วจะย้อนกลับไปทำได้"],
    allowInteraction: true,
  },
  {
    id: "stage-stars",
    route: "/",
    target: "stage-stars",
    appScreen: "dashboard",
    title: "ระบบผ่านด่าน 1–3 ดาว",
    whatIsIt: "ความท้าทาย 3 ระดับของแต่ละด่าน (1 ดาว=เลือกตอบ, 2 ดาว=ฟัง, 3 ดาว=เขียน)",
    howToUse: "กดที่ด่านและเลือกระดับดาวที่ต้องการเล่น",
    rationale: "ผู้เรียนมีพื้นฐานต่างกัน ระบบจึงไม่บังคับให้ทุกคนเริ่มจากข้อเขียนระดับยากเท่ากัน",
    studentBenefit: "ผู้เรียนอ่อนสามารถเริ่มต้นจาก 1 ดาวเพื่อเดินหน้าต่อ ส่วนผู้เรียนที่พร้อมสามารถทดสอบ 3 ดาวได้",
    teacherBenefit: "ครูเห็นได้ชัดเจนว่าผู้เรียนมีทักษะระดับใด (แค่จำได้, ฟังออก, หรือสะกดได้)",
    judgeFocus: ["ทดลองเลือก 1 ดาว และ 3 ดาว จะเห็นรูปแบบคำถามที่ต่างกัน"],
    allowInteraction: true,
  },
  {
    id: "study-camp",
    route: "/",
    target: "study-camp",
    appScreen: "study",
    title: "Study Camp (ค่ายเตรียมความพร้อม)",
    whatIsIt: "พื้นที่เรียนรู้คำศัพท์ (Flashcards) ก่อนเริ่มทำภารกิจ",
    howToUse: "ปัดซ้าย-ขวาเพื่อดูคำศัพท์ ฟังเสียง และดูความหมาย",
    rationale: "ตามหลักจิตวิทยาการเรียนรู้ ไม่ควรส่งผู้เรียนเข้าสู่การประเมินทันทีโดยยังไม่เคยเรียนเนื้อหา",
    studentBenefit: "สร้างความคุ้นเคย ลดความกังวล และช่วยเด็กพื้นฐานอ่อนเตรียมตัวได้อย่างมั่นใจ",
    teacherBenefit: "ใช้เป็นสื่อสอนขึ้นจอ หรือทบทวนคำศัพท์ก่อนทำกิจกรรมในชั้นเรียน",
    judgeFocus: ["ทดลองกดฟังเสียงและดูรูปภาพ ซึ่งเป็นการเตรียมพร้อมสมอง (Priming)"],
    allowInteraction: true,
  },
  {
    id: "stage-1-star",
    route: "/",
    target: "stage-1-star",
    appScreen: "game",
    title: "ระบบด่าน 1 ดาว (Multiple Choice)",
    whatIsIt: "คำถามแบบเลือกตอบ (หาความหมายของศัพท์ หรือ หาศัพท์จากความหมาย)",
    howToUse: "อ่านคำถามและเลือกตัวเลือกที่ถูกต้อง",
    rationale: "ใช้เป็นระดับเริ่มต้นเพื่อลดความกดดันด้านการสะกดคำ",
    studentBenefit: "เข้าถึงง่าย สร้างความมั่นใจในก้าวแรก",
    teacherBenefit: "ใช้วัดความเข้าใจด้านการจำรูปคำเบื้องต้น",
    judgeFocus: ["ระบบจะนำคำที่เรียนจาก Study Camp มาทดสอบที่นี่"],
    allowInteraction: true,
  },
  {
    id: "hint-button",
    route: "/",
    target: "hint-button",
    appScreen: "game",
    title: "Adaptive Hint",
    whatIsIt: "ระบบตัวช่วย เช่น ตัดตัวเลือก เปิดตัวอักษรบางส่วน",
    howToUse: "กดใช้เมื่อไม่แน่ใจคำตอบ",
    rationale: "เด็กรองรับความแตกต่างระหว่างผู้เรียน หากไม่มีตัวช่วย เด็กอาจท้อและหยุดเล่น",
    studentBenefit: "ช่วยให้ผ่านอุปสรรคได้โดยยังต้องออกแรงคิดหาคำตอบ",
    teacherBenefit: "หากนักเรียนใช้ Hint บ่อย ๆ ครูจะมองเห็นจาก Data Dashboard ว่ามีปัญหา",
    judgeFocus: ["เมื่อใช้ Hint ผลคะแนนรวมและระดับ Mastery จะได้รับผลกระทบ เพื่อรักษาความยุติธรรม"],
    allowInteraction: true,
  },
  {
    id: "feedback-result",
    route: "/",
    target: "feedback-result",
    appScreen: "game",
    title: "Feedback หลังตอบ (Immediate Feedback)",
    whatIsIt: "ระบบแสดงผลว่าถูกต้องหรือผิดพลาดทันที พร้อมเฉลย",
    howToUse: "หลังจากกดตอบ ระบบจะแสดงผลและให้กด 'ถัดไป'",
    rationale: "ผู้เรียนควรได้รับข้อมูลย้อนกลับ (Feedback) ขณะที่ยังจำวิธีคิดของตนเองได้ เพื่อแก้ไขความเข้าใจผิดทันที",
    studentBenefit: "รู้ตัวทันทีว่าเข้าใจผิดตรงไหน และเรียนรู้คำตอบที่ถูกต้อง",
    teacherBenefit: "คำที่ตอบผิดจะถูกบันทึกเพื่อใช้วางแผนทบทวนอัตโนมัติ (Spaced Repetition)",
    judgeFocus: ["ลองจงใจตอบผิด เพื่อดูว่าระบบให้เฉลยอย่างไร และไม่ยอมให้ผ่านจนกว่าจะเข้าใจ"],
    allowInteraction: true,
  },
  {
    id: "review-stage",
    route: "/",
    target: "review-stage",
    appScreen: "dashboard",
    title: "Review Stage",
    whatIsIt: "ระบบนำคำศัพท์เก่ากลับมาทบทวน",
    howToUse: "แสดงแทรกเมื่อครบรอบ หรือมีคำศัพท์ที่ถึงกำหนดต้องทบทวน",
    rationale: "การผ่านด่านไม่ได้หมายความว่าจะจำคำศัพท์ได้ระยะยาว (Ebbinghaus Forgetting Curve)",
    studentBenefit: "ได้พบคำเดิมซ้ำในรูปแบบใหม่ ทำให้เปลี่ยนจากความจำระยะสั้นเป็นระยะยาว",
    teacherBenefit: "เห็นคำที่ยังเป็นปัญหาเรื้อรังหลังจากเรียนผ่านมาแล้ว",
    judgeFocus: ["ใน Demo สามารถกดข้ามได้ แต่ในระบบจริง ระบบจะบังคับให้เคลียร์ Spaced Repetition ก่อน"],
    allowInteraction: true,
  },
  {
    id: "card-system",
    route: "/",
    target: "card-system",
    appScreen: "dashboard",
    title: "ระบบการ์ดและไอเทม",
    whatIsIt: "ไอเทมที่เพิ่มกลยุทธ์ เช่น หยุดเวลา, โล่ป้องกัน, หรือแกล้งเพื่อน (เล็กน้อย)",
    howToUse: "เข้าหน้าร้านค้าและช่องเก็บของเพื่อใช้งาน",
    rationale: "เพิ่มแรงจูงใจทางสังคม (Social Interaction) ทำให้เกมน่าติดตาม (Sticky) มากขึ้น",
    studentBenefit: "ฝึกการวางแผน จัดการทรัพยากร และสร้างเสียงหัวเราะกับเพื่อน",
    teacherBenefit: "ใช้เป็นของรางวัลพิเศษในห้องเรียนได้ (มีระบบจำกัดการแกล้งกัน เพื่อไม่ให้เครียด)",
    judgeFocus: ["ทดลองเข้า ShopModal หรือกดใช้งานไอเทม"],
    allowInteraction: true,
  },
  {
    id: "teacher-dashboard",
    route: "/demo/admin",
    target: "teacher-dashboard",
    title: "Teacher Dashboard",
    whatIsIt: "หน้าต่างสรุปข้อมูลสำหรับครู (จัดการเรียนรู้)",
    howToUse: "ดูรายชื่อนักเรียน, เด็กที่ติดด่าน, และคำศัพท์ที่เป็นปัญหาของห้อง",
    rationale: "เปลี่ยนจากข้อมูลดิบจากการเล่นเกม เป็น 'ข้อมูลเพื่อการตัดสินใจสอน' (Actionable Data)",
    studentBenefit: "ได้รับการดูแลอย่างทันท่วงที เช่น ครูอธิบายซ้ำในคำที่ห้องตอบผิดเกิน 50%",
    teacherBenefit: "ใช้วางแผนสอนซ่อมเสริม, แบ่งกลุ่มเด็กเก่ง-อ่อน, และประเมินผลง่ายขึ้น",
    judgeFocus: ["หน้านี้สำหรับ Demo ถูกจำลองขึ้นมาโดยไม่ดึงข้อมูลจริง เพื่อความปลอดภัย"],
    allowInteraction: true,
  },
];
